SELECT
    HOSPITALIZATION.PF_CODE AS "都道府県コード",
    PREFECTURE.PF_NAME AS "都道府県名",
    ROUND(
        CAST(HOSPITALIZATION.INP_YES AS REAL)
        / (
            HOSPITALIZATION.INP_YES
            + HOSPITALIZATION.INP_NO
            + HOSPITALIZATION.UNIDENTIFIED
        ) * 100,
        1
    ) AS "入院率"
FROM HOSPITALIZATION INNER JOIN PREFECTURE
    ON HOSPITALIZATION.PF_CODE = PREFECTURE.PF_CODE
ORDER BY "入院率" DESC, "都道府県コード" ASC;
