SELECT
    ITEM.ITEM_CODE AS CODE,
    CASE
        WHEN ITEM.ITEM_NAME = ITEM_HISTORY.ITEM_NAME THEN NULL ELSE
            ITEM.ITEM_NAME
    END AS NAME
FROM ITEM
LEFT OUTER JOIN ITEM_HISTORY ON ITEM.ITEM_CODE = ITEM_HISTORY.ITEM_CODE
ORDER BY ITEM.ITEM_CODE DESC;
