SELECT
    SALES.SALES_DATE AS SAL_DATE,
    SALES.SALES_NO AS "NO",
    SALES_DTL.ITEM_CODE,
    SALES_DTL.SALES_QTY AS SAL_QTY,
    SALES_DTL.DELIVERED_QTY AS DEL_QTY,
    CASE
        WHEN SALES_DTL.DELIVERED_QTY = 0 THEN '未出荷'
        WHEN SALES_DTL.DELIVERED_QTY < SALES_DTL.SALES_QTY THEN '一部出荷'
        ELSE '出荷済'
    END AS SHIP_STS
FROM SALES
INNER JOIN SALES_DTL ON SALES.SALES_NO = SALES_DTL.SALES_NO
WHERE SALES.SALES_DATE BETWEEN '2024-04-01' AND '2024-04-10'
ORDER BY SALES.SALES_DATE DESC, SALES.SALES_NO ASC, SALES_DTL.ITEM_CODE ASC;
