SELECT
    SLEEP_TIME_DTL.AGE_CODE AS "年齢コード",
    AGE_GRP.AGE_NAME AS "年齢階層名",
    SUM(SLEEP_TIME_DTL.SP_TIME_5) AS "5時間未満",
    SUM(SLEEP_TIME_DTL.SP_TIME_6) AS "5時間以上6時間未満",
    SUM(SLEEP_TIME_DTL.SP_TIME_7) AS "6時間以上7時間未満",
    SUM(SLEEP_TIME_DTL.SP_TIME_8) AS "7時間以上8時間未満",
    SUM(SLEEP_TIME_DTL.SP_TIME_9) AS "8時間以上9時間未満",
    SUM(SLEEP_TIME_DTL.SP_TIME_9OVER) AS "9時間以上"
FROM SLEEP_TIME_DTL
INNER JOIN PREFECTURE
    ON SLEEP_TIME_DTL.PF_CODE = PREFECTURE.PF_CODE AND (
        PREFECTURE.PF_NAME = '北海道'
        OR PREFECTURE.PF_NAME = '青森県'
        OR PREFECTURE.PF_NAME = '岩手県'
        OR PREFECTURE.PF_NAME = '宮城県'
        OR PREFECTURE.PF_NAME = '福島県'
    )
INNER JOIN AGE_GRP
    ON SLEEP_TIME_DTL.AGE_CODE = AGE_GRP.AGE_CODE
GROUP BY SLEEP_TIME_DTL.AGE_CODE
ORDER BY SLEEP_TIME_DTL.AGE_CODE;
