SELECT
    IMMIGRATION.PORT_CODE AS "港コード",
    PORT.PORT_NAME AS "港名",
    SUM(
        CASE WHEN IMMIGRATION.KIND_CODE = '110' THEN IMMIGRATION.AMT ELSE 0 END
    ) AS "入国者数",
    SUM(
        CASE WHEN IMMIGRATION.KIND_CODE = '120' THEN IMMIGRATION.AMT ELSE 0 END
    ) AS "出国者数",
    SUM(CASE WHEN IMMIGRATION.KIND_CODE = '110' THEN IMMIGRATION.AMT ELSE 0 END)
    - SUM(
        CASE WHEN IMMIGRATION.KIND_CODE = '120' THEN IMMIGRATION.AMT ELSE 0 END
    ) AS "差分"
FROM IMMIGRATION
INNER JOIN PORT ON IMMIGRATION.PORT_CODE = PORT.PORT_CODE
WHERE IMMIGRATION.GROUP_CODE = '120'
GROUP BY IMMIGRATION.PORT_CODE
HAVING
    SUM(CASE WHEN IMMIGRATION.KIND_CODE = '110' THEN IMMIGRATION.AMT ELSE 0 END)
    > SUM(
        CASE WHEN IMMIGRATION.KIND_CODE = '120' THEN IMMIGRATION.AMT ELSE 0 END
    )
ORDER BY "差分" DESC, IMMIGRATION.PORT_CODE DESC;
