SELECT
    DRINK_HABITS.PF_CODE AS CODE,
    PREFECTURE.PF_NAME AS NAME,
    ROUND(ROUND(SUM(
        CASE
            WHEN DRINK_HABITS.CATEGORY_CODE = '120' THEN DRINK_HABITS.AMT ELSE 0
        END
    ))
    / ROUND(SUM(
        CASE
            WHEN DRINK_HABITS.CATEGORY_CODE = '110' THEN DRINK_HABITS.AMT ELSE 0
        END
    )) * 100, 1) AS PERCENTAGE
FROM DRINK_HABITS
INNER JOIN PREFECTURE ON DRINK_HABITS.PF_CODE = PREFECTURE.PF_CODE
WHERE DRINK_HABITS.GENDER_CODE IN ('2', '3')
GROUP BY DRINK_HABITS.PF_CODE
ORDER BY PERCENTAGE DESC, CODE DESC;
